# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[(b'FI', b'\xd0\xbc\xd0\xbb\xd0\xb0\xd0\xb4\xd1\x88\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xb3\xd0\xb0'), (b'SE', b'\xd1\x81\xd1\x82\xd0\xb0\xd1\x80\xd1\x88\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xb3\xd0\xb0')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('right_answer', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[(b'FI', b'\xd0\xbc\xd0\xbb\xd0\xb0\xd0\xb4\xd1\x88\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xb3\xd0\xb0'), (b'SE', b'\xd1\x81\xd1\x82\xd0\xb0\xd1\x80\xd1\x88\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xb3\xd0\xb0')], max_length=2)),
                ('image', models.ImageField(blank=True, upload_to=b'images')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='solved_tasks',
            field=models.ManyToManyField(blank=True, to='main.Task'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task'),
        ),
    ]
